spring:
  application:
    name: manage-config
  profiles:
    active: native

server:
  port: 9093


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost